### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: com/comphenix/packetwrapper/wrappers/play/clientbound/WrapperPlayServerEntityTeleport

### ISSUE THREAD

**Issue by LMS5413** [lukalt/PacketWrapper#3]
Hi! Im trying using WrapperTeleportEntity on 1.20.1 but this error an ocurred

```sh
[00:51:13] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to ArgusPlugin v1.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1355) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.network.protocol.game.PacketPlayInFlying.a(SourceFile:114) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.network.protocol.game.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:42) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1152) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.bg(MinecraftServer.java:1131) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1124) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.p_(MinecraftServer.java:1108) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1019) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3856-Spigot-94e187b-b76ceb4]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: com/comphenix/packetwrapper/wrappers/play/clientbound/WrapperPlayServerEntityTeleport
        at org.lmdeveloper.argus.listeners.BukkitEventHandler.onPlayerMovement(BukkitEventHandler.kt:39) ~[?:?]
        at jdk.internal.reflect.GeneratedMethodAccessor51.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        ... 20 more
```
My code:

```kotlin
val location = event.player.location.clone().add(-1.0, 1.0, 0.0)
        val packet = WrapperPlayServerEntityTeleport()
        
        packet.id = 0
        packet.x = location.x
        packet.y = location.y
        packet.z = location.z
        packet.yRot = location.yaw.toInt().toByte()
        packet.xRot = location.pitch.toInt().toByte()

        Bukkit.getServer().onlinePlayers.forEach {
            packet.sendPacket(it)
        }
        ```

**Comment by Withicality** [comment]
have you downloaded the plugin to the server or shaded it to your jar?

**Comment by LMS5413** [comment]
Shaded Jar

**Comment by LMS5413** [comment]
Fixed! Im giving on build.gradle.kts `compileOnly` and no `implementation`. Also, you have discord?
